"use server";

import {
  BookingStatus,
  ConversationChannel,
  ConversationStatus,
  EventInquiryStatus,
  MessageDirection,
  NotificationType,
  OrderStatus,
  OrderType,
  PaymentStatus,
} from "@prisma/client";
import { revalidatePath } from "next/cache";

import { DEFAULT_RESTAURANT_SLUG } from "@/lib/constants";
import { isDatabaseReachable } from "@/lib/database-status";
import { emitRealtimeEvent } from "@/lib/realtime/bus";
import { prisma } from "@/lib/prisma";

async function getRestaurantOrThrow() {
  if (!(await isDatabaseReachable())) {
    throw new Error(
      "Database is unavailable. Start PostgreSQL and run db:push/db:seed before using demo control actions.",
    );
  }

  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug: DEFAULT_RESTAURANT_SLUG,
    },
  });

  if (!restaurant) {
    throw new Error("Mirch Masala restaurant not found. Seed the database first.");
  }

  return restaurant;
}

async function getAnyCustomer(restaurantId: string) {
  const customer = await prisma.customer.findFirst({
    where: { restaurantId },
    orderBy: { createdAt: "asc" },
  });

  if (customer) {
    return customer;
  }

  return prisma.customer.create({
    data: {
      restaurantId,
      firstName: "Demo",
      lastName: "Guest",
      phone: "+91 90000 19999",
      email: "demo.guest@example.com",
      notes: "Autogenerated fallback customer.",
    },
  });
}

function stampOrderNumber() {
  return `MM-${Date.now().toString().slice(-6)}`;
}

function stampReference(prefix: string) {
  return `${prefix}-${Date.now().toString().slice(-5)}`;
}

async function refreshAll() {
  revalidatePath("/");
  revalidatePath("/menu");
  revalidatePath("/dashboard");
  revalidatePath("/orders");
  revalidatePath("/bookings");
  revalidatePath("/events");
  revalidatePath("/kitchen");
  revalidatePath("/analytics");
  revalidatePath("/settings");
  revalidatePath("/track-order");
  revalidatePath("/book-table");
  revalidatePath("/demo/chat");
  revalidatePath("/demo/control");
}

async function createNotification(
  restaurantId: string,
  type: NotificationType,
  title: string,
  body: string,
  href: string,
) {
  await prisma.notification.create({
    data: {
      restaurantId,
      type,
      title,
      body,
      href,
    },
  });
}

export async function createDemoOrderAction() {
  const restaurant = await getRestaurantOrThrow();
  const customer = await getAnyCustomer(restaurant.id);

  const menuItems = await prisma.menuItem.findMany({
    where: {
      restaurantId: restaurant.id,
      isAvailable: true,
    },
    orderBy: { isFeatured: "desc" },
    take: 3,
  });

  const subtotal = menuItems.reduce((sum, item) => sum + item.priceInPaise, 0);
  const tax = Math.round(subtotal * 0.05);
  const deliveryFee = 9900;
  const total = subtotal + tax + deliveryFee;

  const order = await prisma.order.create({
    data: {
      restaurantId: restaurant.id,
      customerId: customer.id,
      orderNumber: stampOrderNumber(),
      orderType: OrderType.DELIVERY,
      status: OrderStatus.PENDING,
      paymentStatus: PaymentStatus.PENDING,
      paymentMethod: "UPI",
      subtotalInPaise: subtotal,
      deliveryFeeInPaise: deliveryFee,
      taxInPaise: tax,
      totalInPaise: total,
      notes: "Created from demo control panel.",
      deliveryAddressText: "Demo delivery route generated from control panel.",
    },
  });

  for (const item of menuItems) {
    await prisma.orderItem.create({
      data: {
        orderId: order.id,
        menuItemId: item.id,
        nameSnapshot: item.name,
        unitPriceInPaise: item.priceInPaise,
        quantity: 1,
        totalPriceInPaise: item.priceInPaise,
      },
    });
  }

  await prisma.payment.create({
    data: {
      restaurantId: restaurant.id,
      orderId: order.id,
      amountInPaise: total,
      status: PaymentStatus.PENDING,
      provider: "Razorpay Demo",
      reference: `${order.orderNumber}-PAY`,
    },
  });

  await createNotification(
    restaurant.id,
    NotificationType.ORDER,
    "New demo order",
    `${order.orderNumber} entered the live queue from demo control.`,
    "/orders",
  );

  await refreshAll();
  emitRealtimeEvent({ type: "order.created", entity: "order", entityId: order.id });
}

export async function simulatePaymentSuccessAction() {
  const restaurant = await getRestaurantOrThrow();
  const order = await prisma.order.findFirst({
    where: {
      restaurantId: restaurant.id,
      paymentStatus: { in: [PaymentStatus.PENDING, PaymentStatus.FAILED] },
    },
    orderBy: { placedAt: "desc" },
  });

  if (!order) {
    return;
  }

  await prisma.order.update({
    where: { id: order.id },
    data: { paymentStatus: PaymentStatus.SUCCESS },
  });

  await prisma.payment.updateMany({
    where: { orderId: order.id },
    data: { status: PaymentStatus.SUCCESS, paidAt: new Date() },
  });

  await createNotification(
    restaurant.id,
    NotificationType.PAYMENT,
    "Payment captured",
    `${order.orderNumber} payment was marked successful.`,
    "/orders",
  );

  await refreshAll();
  emitRealtimeEvent({ type: "payment.success", entity: "order", entityId: order.id });
}

export async function simulatePaymentFailureAction() {
  const restaurant = await getRestaurantOrThrow();
  const order = await prisma.order.findFirst({
    where: {
      restaurantId: restaurant.id,
      paymentStatus: { in: [PaymentStatus.PENDING, PaymentStatus.SUCCESS] },
    },
    orderBy: { placedAt: "desc" },
  });

  if (!order) {
    return;
  }

  await prisma.order.update({
    where: { id: order.id },
    data: { paymentStatus: PaymentStatus.FAILED },
  });

  await prisma.payment.updateMany({
    where: { orderId: order.id },
    data: { status: PaymentStatus.FAILED, failureReason: "Simulated control panel failure." },
  });

  await refreshAll();
  emitRealtimeEvent({ type: "payment.failed", entity: "order", entityId: order.id });
}

export async function managerApproveOrderAction() {
  const restaurant = await getRestaurantOrThrow();
  const order = await prisma.order.findFirst({
    where: {
      restaurantId: restaurant.id,
      status: OrderStatus.PENDING,
    },
    orderBy: { placedAt: "asc" },
  });

  if (!order) {
    return;
  }

  await prisma.order.update({
    where: { id: order.id },
    data: { status: OrderStatus.CONFIRMED },
  });

  await refreshAll();
  emitRealtimeEvent({ type: "order.approved", entity: "order", entityId: order.id });
}

export async function advanceKitchenOrderAction() {
  const restaurant = await getRestaurantOrThrow();
  const order = await prisma.order.findFirst({
    where: {
      restaurantId: restaurant.id,
      status: { in: [OrderStatus.CONFIRMED, OrderStatus.PREPARING, OrderStatus.PENDING] },
    },
    orderBy: { placedAt: "asc" },
  });

  if (!order) {
    return;
  }

  const nextStatus =
    order.status === OrderStatus.PREPARING
      ? OrderStatus.READY
      : OrderStatus.PREPARING;

  await prisma.order.update({
    where: { id: order.id },
    data: {
      status: nextStatus,
      readyAt: nextStatus === OrderStatus.READY ? new Date() : null,
    },
  });

  await refreshAll();
  emitRealtimeEvent({ type: "kitchen.progressed", entity: "order", entityId: order.id });
}

export async function advanceDeliveryOrderAction() {
  const restaurant = await getRestaurantOrThrow();
  const order = await prisma.order.findFirst({
    where: {
      restaurantId: restaurant.id,
      status: { in: [OrderStatus.READY, OrderStatus.OUT_FOR_DELIVERY] },
      orderType: OrderType.DELIVERY,
    },
    orderBy: { placedAt: "asc" },
  });

  if (!order) {
    return;
  }

  const nextStatus =
    order.status === OrderStatus.READY
      ? OrderStatus.OUT_FOR_DELIVERY
      : OrderStatus.COMPLETED;

  await prisma.order.update({
    where: { id: order.id },
    data: {
      status: nextStatus,
      deliveredAt: nextStatus === OrderStatus.COMPLETED ? new Date() : null,
    },
  });

  await refreshAll();
  emitRealtimeEvent({ type: "delivery.progressed", entity: "order", entityId: order.id });
}

export async function createDemoBookingAction() {
  const restaurant = await getRestaurantOrThrow();
  const customer = await getAnyCustomer(restaurant.id);

  const booking = await prisma.tableBooking.create({
    data: {
      restaurantId: restaurant.id,
      customerId: customer.id,
      bookingReference: stampReference("BK"),
      guestCount: 6,
      bookingDateTime: new Date(Date.now() + 1000 * 60 * 60 * 24),
      status: BookingStatus.PENDING,
      seatingPreference: "Private lounge",
      specialOccasion: "Control panel booking",
      source: "demo-control",
      notes: "Created from demo control panel.",
    },
  });

  await createNotification(
    restaurant.id,
    NotificationType.BOOKING,
    "New booking request",
    `${booking.bookingReference} was added from the demo control panel.`,
    "/bookings",
  );

  await refreshAll();
  emitRealtimeEvent({ type: "booking.created", entity: "booking", entityId: booking.id });
}

export async function createDemoEventInquiryAction() {
  const restaurant = await getRestaurantOrThrow();
  const customer = await getAnyCustomer(restaurant.id);

  const event = await prisma.eventInquiry.create({
    data: {
      restaurantId: restaurant.id,
      customerId: customer.id,
      inquiryReference: stampReference("EV"),
      eventType: "Corporate Dinner",
      guestCount: 40,
      eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 21),
      budgetRange: "INR 2L - 3L",
      status: EventInquiryStatus.NEW,
      venuePreference: "Main dining buyout",
      source: "demo-control",
      notes: "Generated from the demo control panel for pipeline simulation.",
    },
  });

  await createNotification(
    restaurant.id,
    NotificationType.EVENT,
    "New event lead",
    `${event.inquiryReference} entered the events pipeline.`,
    "/events",
  );

  await refreshAll();
  emitRealtimeEvent({ type: "event.created", entity: "event", entityId: event.id });
}

async function createConversationFlow({
  summary,
  messages,
  createRecord,
}: {
  summary: string;
  messages: string[];
  createRecord?: (restaurantId: string, customerId: string) => Promise<void>;
}) {
  const restaurant = await getRestaurantOrThrow();
  const customer = await getAnyCustomer(restaurant.id);

  const conversation = await prisma.conversation.create({
    data: {
      restaurantId: restaurant.id,
      customerId: customer.id,
      channel: ConversationChannel.WHATSAPP,
      status: ConversationStatus.OPEN,
      summary,
      lastMessageAt: new Date(),
    },
  });

  for (const [index, message] of messages.entries()) {
    await prisma.messageLog.create({
      data: {
        restaurantId: restaurant.id,
        conversationId: conversation.id,
        direction:
          index % 2 === 0 ? MessageDirection.INBOUND : MessageDirection.OUTBOUND,
        content: message,
      },
    });
  }

  if (createRecord) {
    await createRecord(restaurant.id, customer.id);
  }

  await refreshAll();
  emitRealtimeEvent({
    type: "conversation.updated",
    entity: "conversation",
    entityId: conversation.id,
  });
}

export async function demoChatOrderFlowAction() {
  await createConversationFlow({
    summary: "Guest used quick reply flow to place a delivery order.",
    messages: [
      "I want to order dinner for delivery.",
      "Absolutely. I have placed your guided order and queued it for the kitchen.",
    ],
    createRecord: async (restaurantId, customerId) => {
      const topItems = await prisma.menuItem.findMany({
        where: { restaurantId, isFeatured: true },
        take: 2,
      });
      const subtotal = topItems.reduce((sum, item) => sum + item.priceInPaise, 0);
      const tax = Math.round(subtotal * 0.05);
      const total = subtotal + tax + 9900;

      const order = await prisma.order.create({
        data: {
          restaurantId,
          customerId,
          orderNumber: stampOrderNumber(),
          orderType: OrderType.DELIVERY,
          status: OrderStatus.PENDING,
          paymentStatus: PaymentStatus.PENDING,
          subtotalInPaise: subtotal,
          deliveryFeeInPaise: 9900,
          taxInPaise: tax,
          totalInPaise: total,
          notes: "Created from demo chat order flow.",
        },
      });

      for (const item of topItems) {
        await prisma.orderItem.create({
          data: {
            orderId: order.id,
            menuItemId: item.id,
            nameSnapshot: item.name,
            unitPriceInPaise: item.priceInPaise,
            quantity: 1,
            totalPriceInPaise: item.priceInPaise,
          },
        });
      }
    },
  });
}

export async function demoChatBookingFlowAction() {
  await createConversationFlow({
    summary: "Guest used quick reply flow for a table booking.",
    messages: [
      "Book a table for tomorrow night.",
      "Your booking request has been created and sent to the manager.",
    ],
    createRecord: async (restaurantId, customerId) => {
      await prisma.tableBooking.create({
        data: {
          restaurantId,
          customerId,
          bookingReference: stampReference("BK"),
          guestCount: 4,
          bookingDateTime: new Date(Date.now() + 1000 * 60 * 60 * 26),
          status: BookingStatus.PENDING,
          seatingPreference: "Window",
          specialOccasion: "Date night",
          source: "demo-chat",
          notes: "Created from demo chat booking flow.",
        },
      });
    },
  });
}

export async function demoChatPartyFlowAction() {
  await createConversationFlow({
    summary: "Birthday or party inquiry from guided quick reply flow.",
    messages: [
      "I need a birthday setup for 12 guests.",
      "I have created your celebration request for the events team.",
    ],
    createRecord: async (restaurantId, customerId) => {
      await prisma.eventInquiry.create({
        data: {
          restaurantId,
          customerId,
          inquiryReference: stampReference("EV"),
          eventType: "Birthday Dinner",
          guestCount: 12,
          eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10),
          budgetRange: "INR 75k - 1L",
          status: EventInquiryStatus.NEW,
          venuePreference: "Private lounge",
          source: "demo-chat",
          notes: "Created from birthday quick reply flow.",
        },
      });
    },
  });
}

export async function demoChatWeddingFlowAction() {
  await createConversationFlow({
    summary: "Wedding inquiry submitted from chat flow.",
    messages: [
      "Can you host a wedding welcome dinner?",
      "Yes. I have passed your wedding inquiry to our events manager.",
    ],
    createRecord: async (restaurantId, customerId) => {
      await prisma.eventInquiry.create({
        data: {
          restaurantId,
          customerId,
          inquiryReference: stampReference("EV"),
          eventType: "Wedding Welcome Dinner",
          guestCount: 80,
          eventDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 28),
          budgetRange: "INR 3L+",
          status: EventInquiryStatus.NEW,
          venuePreference: "Full buyout",
          source: "demo-chat",
          notes: "Created from wedding inquiry quick reply flow.",
        },
      });
    },
  });
}

export async function demoChatMenuFlowAction() {
  await createConversationFlow({
    summary: "Guest asked for the menu in chat.",
    messages: [
      "Can you send me your signature dishes?",
      "I have shared our featured tandoor, curry, biryani, and dessert recommendations.",
    ],
  });
}

export async function demoChatContactFlowAction() {
  await createConversationFlow({
    summary: "Guest requested contact details and location details.",
    messages: [
      "What are your contact details and timings?",
      "I have shared our phone, WhatsApp, address, and opening hours.",
    ],
  });
}
