export const demoRestaurant = {
  name: "Mirch Masala",
  slug: "mirch-masala",
  tagline: "Progressive Indian dining, built for memorable nights.",
  description:
    "Mirch Masala brings premium Indian cuisine, smart operations, and guest-first hospitality into one polished restaurant system.",
  phone: "+91 98765 43210",
  email: "hello@mirchmasala.demo",
  whatsapp: "+91 98765 43210",
  addressLine1: "12 Residency Road",
  addressLine2: "Ashok Nagar",
  city: "Bengaluru",
  state: "Karnataka",
  postalCode: "560025",
  country: "India",
  currency: "INR",
  timezone: "Asia/Kolkata",
  accentColor: "#F59E0B",
  secondaryColor: "#F97316",
  heroStats: [
    { label: "Avg rating", value: "4.9/5" },
    { label: "Orders fulfilled", value: "18k+" },
    { label: "Private events", value: "320+" },
  ],
};

export const demoUsers = [
  {
    role: "OWNER",
    name: "Aarav Malhotra",
    email: "owner@mirchmasala.demo",
    title: "Owner",
  },
  {
    role: "MANAGER",
    name: "Sana Qureshi",
    email: "manager@mirchmasala.demo",
    title: "Floor Manager",
  },
  {
    role: "KITCHEN",
    name: "Chef Rohan Kapoor",
    email: "kitchen@mirchmasala.demo",
    title: "Head Kitchen",
  },
  {
    role: "DELIVERY",
    name: "Arjun Singh",
    email: "delivery@mirchmasala.demo",
    title: "Delivery Rider",
  },
] as const;

export const demoBusinessHours = [
  { dayOfWeek: 0, opensAt: "12:00", closesAt: "22:30", isClosed: false },
  { dayOfWeek: 1, opensAt: "12:00", closesAt: "22:30", isClosed: false },
  { dayOfWeek: 2, opensAt: "12:00", closesAt: "22:30", isClosed: false },
  { dayOfWeek: 3, opensAt: "12:00", closesAt: "22:30", isClosed: false },
  { dayOfWeek: 4, opensAt: "12:00", closesAt: "23:00", isClosed: false },
  { dayOfWeek: 5, opensAt: "12:00", closesAt: "23:30", isClosed: false },
  { dayOfWeek: 6, opensAt: "12:00", closesAt: "23:30", isClosed: false },
];

export const demoDeliveryZones = [
  {
    name: "Central Bengaluru",
    postalCodes: ["560001", "560002", "560025"],
    minOrderInPaise: 80000,
    deliveryFeeInPaise: 9900,
    estimatedMinutes: 32,
  },
  {
    name: "Indiranagar & East",
    postalCodes: ["560038", "560008", "560075"],
    minOrderInPaise: 100000,
    deliveryFeeInPaise: 12900,
    estimatedMinutes: 40,
  },
  {
    name: "Outer Ring Premium",
    postalCodes: ["560103", "560066", "560087"],
    minOrderInPaise: 130000,
    deliveryFeeInPaise: 16900,
    estimatedMinutes: 48,
  },
];

export const demoCategories = [
  {
    name: "Signature Starters",
    slug: "signature-starters",
    description: "Small plates with smoke, crunch, and house spice blends.",
    sortOrder: 1,
  },
  {
    name: "Tandoor & Grill",
    slug: "tandoor-grill",
    description: "Charred premium cuts and clay-oven classics.",
    sortOrder: 2,
  },
  {
    name: "Royal Curries",
    slug: "royal-curries",
    description: "Rich gravies, slow reductions, and signature sauces.",
    sortOrder: 3,
  },
  {
    name: "Biryani Atelier",
    slug: "biryani-atelier",
    description: "Layered fragrant rice dishes finished with dum cooking.",
    sortOrder: 4,
  },
  {
    name: "Breads & Sides",
    slug: "breads-sides",
    description: "Hand-stretched naans, breads, and table accompaniments.",
    sortOrder: 5,
  },
  {
    name: "Desserts & Pour",
    slug: "desserts-pour",
    description: "Endings worth staying for, from mithai to mocktails.",
    sortOrder: 6,
  },
];

export const demoMenuItems = [
  {
    categorySlug: "signature-starters",
    name: "Truffle Dahi Puri",
    slug: "truffle-dahi-puri",
    description: "Crisp puri shells with spiced yogurt, tamarind pearls, and truffle sev.",
    priceInPaise: 42000,
    spiceLevel: 1,
    isVegetarian: true,
    isFeatured: true,
    dietaryTags: ["vegetarian", "signature"],
    prepTimeMinutes: 10,
  },
  {
    categorySlug: "signature-starters",
    name: "Crisp Lotus Root Chaat",
    slug: "crisp-lotus-root-chaat",
    description: "Lotus root shards tossed with green chutney, pomegranate, and masala dust.",
    priceInPaise: 39000,
    spiceLevel: 2,
    isVegetarian: true,
    dietaryTags: ["vegetarian", "chaat"],
    prepTimeMinutes: 12,
  },
  {
    categorySlug: "signature-starters",
    name: "Malai Broccoli Roast",
    slug: "malai-broccoli-roast",
    description: "Charred broccoli in hung curd marinade with toasted almond crumble.",
    priceInPaise: 46000,
    spiceLevel: 1,
    isVegetarian: true,
    dietaryTags: ["vegetarian", "gluten-free"],
    prepTimeMinutes: 14,
  },
  {
    categorySlug: "signature-starters",
    name: "Gunpowder Prawns",
    slug: "gunpowder-prawns",
    description: "Crispy tiger prawns with curry leaf aioli and podi spice.",
    priceInPaise: 68000,
    spiceLevel: 3,
    isVegetarian: false,
    isFeatured: true,
    dietaryTags: ["seafood", "signature"],
    prepTimeMinutes: 16,
  },
  {
    categorySlug: "signature-starters",
    name: "Lamb Seekh Sliders",
    slug: "lamb-seekh-sliders",
    description: "Mini brioche sliders with seekh kebab, onion jam, and mint relish.",
    priceInPaise: 54000,
    spiceLevel: 2,
    isVegetarian: false,
    dietaryTags: ["lamb"],
    prepTimeMinutes: 15,
  },
  {
    categorySlug: "tandoor-grill",
    name: "Old Delhi Paneer Tikka",
    slug: "old-delhi-paneer-tikka",
    description: "Paneer cubes with bell peppers in a smoky chili-cashew marinade.",
    priceInPaise: 52000,
    spiceLevel: 2,
    isVegetarian: true,
    dietaryTags: ["vegetarian", "tandoor"],
    prepTimeMinutes: 18,
  },
  {
    categorySlug: "tandoor-grill",
    name: "Murgh Makhmali Kebab",
    slug: "murgh-makhmali-kebab",
    description: "Silky chicken kebabs finished with charred cream and kasuri methi.",
    priceInPaise: 62000,
    spiceLevel: 1,
    isVegetarian: false,
    isFeatured: true,
    dietaryTags: ["chicken", "tandoor"],
    prepTimeMinutes: 20,
  },
  {
    categorySlug: "tandoor-grill",
    name: "Kasundi Salmon Tikka",
    slug: "kasundi-salmon-tikka",
    description: "Salmon fillet with Bengali mustard glaze and burnt citrus.",
    priceInPaise: 79000,
    spiceLevel: 2,
    isVegetarian: false,
    dietaryTags: ["seafood", "grill"],
    prepTimeMinutes: 18,
  },
  {
    categorySlug: "tandoor-grill",
    name: "Smoked Lamb Chops",
    slug: "smoked-lamb-chops",
    description: "Rosemary-smoked chops lacquered with black cardamom glaze.",
    priceInPaise: 98000,
    spiceLevel: 2,
    isVegetarian: false,
    dietaryTags: ["lamb", "signature"],
    prepTimeMinutes: 22,
  },
  {
    categorySlug: "tandoor-grill",
    name: "Tandoori Jhinga Platter",
    slug: "tandoori-jhinga-platter",
    description: "Jumbo prawns marinated in pickled chili and saffron yogurt.",
    priceInPaise: 92000,
    spiceLevel: 3,
    isVegetarian: false,
    dietaryTags: ["seafood", "tandoor"],
    prepTimeMinutes: 20,
  },
  {
    categorySlug: "royal-curries",
    name: "Mirch Masala Butter Chicken",
    slug: "mirch-masala-butter-chicken",
    description: "House signature makhani with charred chicken and saffron cream.",
    priceInPaise: 68000,
    spiceLevel: 2,
    isVegetarian: false,
    isFeatured: true,
    dietaryTags: ["chicken", "signature"],
    prepTimeMinutes: 18,
  },
  {
    categorySlug: "royal-curries",
    name: "Nalli Nihari Reduction",
    slug: "nalli-nihari-reduction",
    description: "Slow-braised lamb shank in a deep marrow-enriched nihari sauce.",
    priceInPaise: 86000,
    spiceLevel: 3,
    isVegetarian: false,
    dietaryTags: ["lamb"],
    prepTimeMinutes: 20,
  },
  {
    categorySlug: "royal-curries",
    name: "Paneer Lababdar Noir",
    slug: "paneer-lababdar-noir",
    description: "Tomato-cashew gravy with blackened paneer and fenugreek smoke.",
    priceInPaise: 56000,
    spiceLevel: 2,
    isVegetarian: true,
    dietaryTags: ["vegetarian"],
    prepTimeMinutes: 16,
  },
  {
    categorySlug: "royal-curries",
    name: "Coastal Coconut Prawn Curry",
    slug: "coastal-coconut-prawn-curry",
    description: "Kerala-style coconut curry with tamarind and curry leaf oil.",
    priceInPaise: 76000,
    spiceLevel: 3,
    isVegetarian: false,
    dietaryTags: ["seafood"],
    prepTimeMinutes: 17,
  },
  {
    categorySlug: "royal-curries",
    name: "Dal Mirch Reserve",
    slug: "dal-mirch-reserve",
    description: "Overnight black lentils simmered for 18 hours with brown butter.",
    priceInPaise: 42000,
    spiceLevel: 1,
    isVegetarian: true,
    dietaryTags: ["vegetarian", "signature"],
    prepTimeMinutes: 14,
  },
  {
    categorySlug: "royal-curries",
    name: "Jackfruit Rogan Roast",
    slug: "jackfruit-rogan-roast",
    description: "Young jackfruit in Kashmiri chili rogan with fennel and yogurt.",
    priceInPaise: 51000,
    spiceLevel: 2,
    isVegetarian: true,
    dietaryTags: ["vegan-friendly"],
    prepTimeMinutes: 16,
  },
  {
    categorySlug: "biryani-atelier",
    name: "Saffron Murgh Dum Biryani",
    slug: "saffron-murgh-dum-biryani",
    description: "Fragrant basmati layered with chicken, saffron milk, and mint.",
    priceInPaise: 72000,
    spiceLevel: 2,
    isVegetarian: false,
    isFeatured: true,
    dietaryTags: ["biryani", "chicken"],
    prepTimeMinutes: 24,
  },
  {
    categorySlug: "biryani-atelier",
    name: "Nizami Lamb Biryani",
    slug: "nizami-lamb-biryani",
    description: "Tender lamb dum-cooked with mace, fried onion, and rose petals.",
    priceInPaise: 86000,
    spiceLevel: 3,
    isVegetarian: false,
    dietaryTags: ["biryani", "lamb"],
    prepTimeMinutes: 26,
  },
  {
    categorySlug: "biryani-atelier",
    name: "Subz Noorani Biryani",
    slug: "subz-noorani-biryani",
    description: "Garden vegetables, browned onion, and mint sealed under flaky dough.",
    priceInPaise: 59000,
    spiceLevel: 1,
    isVegetarian: true,
    dietaryTags: ["biryani", "vegetarian"],
    prepTimeMinutes: 22,
  },
  {
    categorySlug: "biryani-atelier",
    name: "Prawn Malabar Biryani",
    slug: "prawn-malabar-biryani",
    description: "Spiced prawns with short-grain rice, coconut, and crispy shallots.",
    priceInPaise: 79000,
    spiceLevel: 3,
    isVegetarian: false,
    dietaryTags: ["biryani", "seafood"],
    prepTimeMinutes: 22,
  },
  {
    categorySlug: "breads-sides",
    name: "Truffle Garlic Naan",
    slug: "truffle-garlic-naan",
    description: "Butter naan finished with roasted garlic confit and truffle mist.",
    priceInPaise: 18000,
    spiceLevel: 0,
    isVegetarian: true,
    dietaryTags: ["bread"],
    prepTimeMinutes: 8,
  },
  {
    categorySlug: "breads-sides",
    name: "Roomali Rosette",
    slug: "roomali-rosette",
    description: "Soft roomali folded tableside with sesame ghee.",
    priceInPaise: 15000,
    spiceLevel: 0,
    isVegetarian: true,
    dietaryTags: ["bread"],
    prepTimeMinutes: 8,
  },
  {
    categorySlug: "breads-sides",
    name: "Burrata Kulcha",
    slug: "burrata-kulcha",
    description: "Stuffed kulcha with burrata, kasundi, and coriander butter.",
    priceInPaise: 26000,
    spiceLevel: 1,
    isVegetarian: true,
    dietaryTags: ["bread", "signature"],
    prepTimeMinutes: 10,
  },
  {
    categorySlug: "breads-sides",
    name: "Jeera Pulao",
    slug: "jeera-pulao",
    description: "Aromatic basmati rice with clarified butter and toasted cumin.",
    priceInPaise: 24000,
    spiceLevel: 0,
    isVegetarian: true,
    dietaryTags: ["rice"],
    prepTimeMinutes: 10,
  },
  {
    categorySlug: "breads-sides",
    name: "Smoked Burrani Raita",
    slug: "smoked-burrani-raita",
    description: "Roasted garlic yogurt raita with smoked chili oil.",
    priceInPaise: 16000,
    spiceLevel: 1,
    isVegetarian: true,
    dietaryTags: ["side"],
    prepTimeMinutes: 6,
  },
  {
    categorySlug: "desserts-pour",
    name: "Saffron Tres Leches Rasmalai",
    slug: "saffron-tres-leches-rasmalai",
    description: "Rasmalai sponge soaked in saffron milk with pistachio praline.",
    priceInPaise: 34000,
    spiceLevel: 0,
    isVegetarian: true,
    isFeatured: true,
    dietaryTags: ["dessert"],
    prepTimeMinutes: 8,
  },
  {
    categorySlug: "desserts-pour",
    name: "Dark Chocolate Gulab Jamun",
    slug: "dark-chocolate-gulab-jamun",
    description: "Warm gulab jamuns with dark chocolate ganache and sea salt.",
    priceInPaise: 32000,
    spiceLevel: 0,
    isVegetarian: true,
    dietaryTags: ["dessert"],
    prepTimeMinutes: 8,
  },
  {
    categorySlug: "desserts-pour",
    name: "Cardamom Panna Cotta",
    slug: "cardamom-panna-cotta",
    description: "Silken panna cotta with cardamom, mango gel, and basil seeds.",
    priceInPaise: 30000,
    spiceLevel: 0,
    isVegetarian: true,
    dietaryTags: ["dessert"],
    prepTimeMinutes: 8,
  },
  {
    categorySlug: "desserts-pour",
    name: "Rose & Jamun Fizz",
    slug: "rose-jamun-fizz",
    description: "Sparkling cooler with rose, jamun, lime, and Himalayan salt.",
    priceInPaise: 22000,
    spiceLevel: 0,
    isVegetarian: true,
    dietaryTags: ["mocktail"],
    prepTimeMinutes: 5,
  },
  {
    categorySlug: "desserts-pour",
    name: "Smoked Kesar Lassi",
    slug: "smoked-kesar-lassi",
    description: "Silky saffron lassi with smoked cream and pistachio dust.",
    priceInPaise: 24000,
    spiceLevel: 0,
    isVegetarian: true,
    dietaryTags: ["beverage"],
    prepTimeMinutes: 5,
  },
  {
    categorySlug: "desserts-pour",
    name: "Filter Coffee Old Fashioned Zero",
    slug: "filter-coffee-old-fashioned-zero",
    description: "Spirit-free coffee cocktail with jaggery bitters and orange zest.",
    priceInPaise: 26000,
    spiceLevel: 0,
    isVegetarian: true,
    dietaryTags: ["beverage"],
    prepTimeMinutes: 6,
  },
];

export const demoCustomers = [
  {
    firstName: "Ishita",
    lastName: "Rao",
    phone: "+91 90000 10001",
    email: "ishita.rao@example.com",
    notes: "Prefers mild spice, vegetarian add-ons.",
    addresses: [
      {
        label: "Home",
        line1: "28 Lavelle Road",
        city: "Bengaluru",
        state: "Karnataka",
        postalCode: "560001",
        country: "India",
        isDefault: true,
      },
    ],
  },
  {
    firstName: "Kabir",
    lastName: "Sethi",
    phone: "+91 90000 10002",
    email: "kabir.sethi@example.com",
    notes: "Usually orders biryani and mocktails.",
    addresses: [
      {
        label: "Residence",
        line1: "91 Indiranagar 12th Main",
        city: "Bengaluru",
        state: "Karnataka",
        postalCode: "560038",
        country: "India",
        isDefault: true,
      },
    ],
  },
  {
    firstName: "Maya",
    lastName: "Fernandes",
    phone: "+91 90000 10003",
    email: "maya.fernandes@example.com",
    notes: "Frequently books private dining.",
    addresses: [
      {
        label: "Studio",
        line1: "14 Museum Road",
        city: "Bengaluru",
        state: "Karnataka",
        postalCode: "560025",
        country: "India",
        isDefault: true,
      },
    ],
  },
  {
    firstName: "Rohan",
    lastName: "Kapadia",
    phone: "+91 90000 10004",
    email: "rohan.kapadia@example.com",
    notes: "Corporate lunch organizer.",
    addresses: [
      {
        label: "Office",
        line1: "11 Embassy Golf Links",
        city: "Bengaluru",
        state: "Karnataka",
        postalCode: "560071",
        country: "India",
        isDefault: true,
      },
    ],
  },
  {
    firstName: "Anika",
    lastName: "Bose",
    phone: "+91 90000 10005",
    email: "anika.bose@example.com",
    notes: "Birthday celebration lead.",
    addresses: [
      {
        label: "Home",
        line1: "55 Koramangala 4th Block",
        city: "Bengaluru",
        state: "Karnataka",
        postalCode: "560034",
        country: "India",
        isDefault: true,
      },
    ],
  },
];

export const demoTestimonials = [
  {
    name: "Nikita Khanna",
    quote:
      "The food lands like a luxury dining experience, but the operations feel even more premium. Every order feels cared for.",
  },
  {
    name: "Arjun Mehta",
    quote:
      "From table booking to WhatsApp updates, Mirch Masala makes the whole guest journey feel polished and effortless.",
  },
  {
    name: "Sara D'Souza",
    quote:
      "One of the few restaurant demos that actually looks deployable. Beautiful website, clear kitchen flow, and smart controls.",
  },
];

export const demoOrderBlueprints = [
  {
    orderNumber: "MM-1001",
    customerPhone: "+91 90000 10001",
    orderType: "DELIVERY",
    status: "PENDING",
    paymentStatus: "PENDING",
    paymentMethod: "UPI",
    notes: "Call on arrival. Extra mint chutney.",
    items: [
      { menuSlug: "truffle-dahi-puri", quantity: 1 },
      { menuSlug: "mirch-masala-butter-chicken", quantity: 1 },
      { menuSlug: "truffle-garlic-naan", quantity: 2 },
    ],
  },
  {
    orderNumber: "MM-1002",
    customerPhone: "+91 90000 10002",
    orderType: "PICKUP",
    status: "PREPARING",
    paymentStatus: "SUCCESS",
    paymentMethod: "Card",
    notes: "Pickup at 8:15 PM.",
    items: [
      { menuSlug: "saffron-murgh-dum-biryani", quantity: 1 },
      { menuSlug: "smoked-kesar-lassi", quantity: 2 },
    ],
  },
  {
    orderNumber: "MM-1003",
    customerPhone: "+91 90000 10003",
    orderType: "DINE_IN",
    status: "READY",
    paymentStatus: "PENDING",
    paymentMethod: "Table",
    notes: "Table 7 tasting menu add-on.",
    items: [
      { menuSlug: "gunpowder-prawns", quantity: 1 },
      { menuSlug: "nalli-nihari-reduction", quantity: 1 },
      { menuSlug: "jeera-pulao", quantity: 1 },
    ],
  },
  {
    orderNumber: "MM-1004",
    customerPhone: "+91 90000 10004",
    orderType: "DELIVERY",
    status: "OUT_FOR_DELIVERY",
    paymentStatus: "SUCCESS",
    paymentMethod: "UPI",
    notes: "Office delivery gate 2.",
    items: [
      { menuSlug: "old-delhi-paneer-tikka", quantity: 1 },
      { menuSlug: "paneer-lababdar-noir", quantity: 1 },
      { menuSlug: "burrata-kulcha", quantity: 2 },
    ],
  },
  {
    orderNumber: "MM-1005",
    customerPhone: "+91 90000 10005",
    orderType: "DELIVERY",
    status: "COMPLETED",
    paymentStatus: "SUCCESS",
    paymentMethod: "Card",
    notes: "Birthday dessert surprise.",
    items: [
      { menuSlug: "murgh-makhmali-kebab", quantity: 1 },
      { menuSlug: "subz-noorani-biryani", quantity: 1 },
      { menuSlug: "saffron-tres-leches-rasmalai", quantity: 1 },
    ],
  },
  {
    orderNumber: "MM-1006",
    customerPhone: "+91 90000 10001",
    orderType: "DELIVERY",
    status: "CONFIRMED",
    paymentStatus: "FAILED",
    paymentMethod: "Card",
    notes: "Retry payment link sent.",
    items: [
      { menuSlug: "coastal-coconut-prawn-curry", quantity: 1 },
      { menuSlug: "roomali-rosette", quantity: 2 },
    ],
  },
];

export const demoBookings = [
  {
    bookingReference: "BK-2201",
    customerPhone: "+91 90000 10003",
    guestCount: 4,
    bookingDateOffsetDays: 1,
    bookingHour: 20,
    status: "CONFIRMED",
    seatingPreference: "Window",
    specialOccasion: "Anniversary dinner",
    source: "website",
  },
  {
    bookingReference: "BK-2202",
    customerPhone: "+91 90000 10005",
    guestCount: 10,
    bookingDateOffsetDays: 2,
    bookingHour: 19,
    status: "PENDING",
    seatingPreference: "Private room",
    specialOccasion: "Birthday dinner",
    source: "chat",
  },
  {
    bookingReference: "BK-2203",
    customerPhone: "+91 90000 10002",
    guestCount: 2,
    bookingDateOffsetDays: 0,
    bookingHour: 21,
    status: "SEATED",
    seatingPreference: "Patio",
    specialOccasion: "Date night",
    source: "whatsapp",
  },
];

export const demoEventInquiries = [
  {
    inquiryReference: "EV-3301",
    customerPhone: "+91 90000 10005",
    eventType: "Birthday Dinner",
    guestCount: 18,
    eventDateOffsetDays: 12,
    budgetRange: "INR 75k - 1L",
    status: "CONTACTED",
    venuePreference: "Private dining lounge",
    source: "chat",
    notes: "Needs projector and custom dessert moment.",
  },
  {
    inquiryReference: "EV-3302",
    customerPhone: "+91 90000 10004",
    eventType: "Corporate Dinner",
    guestCount: 30,
    eventDateOffsetDays: 18,
    budgetRange: "INR 1.5L - 2L",
    status: "PROPOSAL_SENT",
    venuePreference: "Main dining buyout",
    source: "website",
    notes: "Prefers fixed menu and branded welcome cards.",
  },
  {
    inquiryReference: "EV-3303",
    customerPhone: "+91 90000 10003",
    eventType: "Wedding Welcome Dinner",
    guestCount: 60,
    eventDateOffsetDays: 35,
    budgetRange: "INR 3L+",
    status: "NEW",
    venuePreference: "Full restaurant buyout",
    source: "whatsapp",
    notes: "Interested in live chaat and dessert stations.",
  },
];

export const demoConversationBlueprints = [
  {
    customerPhone: "+91 90000 10001",
    channel: "WHATSAPP",
    summary: "Delivery order support and tracking.",
    messages: [
      { direction: "INBOUND", content: "Hi, can I place an order for tonight?" },
      {
        direction: "OUTBOUND",
        content: "Absolutely. I can help with delivery, pickup, or table booking.",
      },
      {
        direction: "SYSTEM",
        content: "Created order MM-1001 from guided WhatsApp-style flow.",
      },
    ],
  },
  {
    customerPhone: "+91 90000 10005",
    channel: "WHATSAPP",
    summary: "Birthday dinner inquiry with private dining request.",
    messages: [
      { direction: "INBOUND", content: "I need a table for 10 for a birthday dinner." },
      {
        direction: "OUTBOUND",
        content: "We have a private lounge available. I have logged your booking request.",
      },
      {
        direction: "SYSTEM",
        content: "Created booking BK-2202 and event inquiry EV-3301.",
      },
    ],
  },
  {
    customerPhone: "+91 90000 10003",
    channel: "WEBSITE",
    summary: "Wedding welcome dinner inquiry.",
    messages: [
      { direction: "INBOUND", content: "Can you host a wedding welcome dinner for 60 guests?" },
      {
        direction: "OUTBOUND",
        content: "Yes. Our events manager will send a proposal with layout and menu options.",
      },
      {
        direction: "SYSTEM",
        content: "Event inquiry EV-3303 created from demo chat flow.",
      },
    ],
  },
];
